import {test} from 'node:test';import assert from 'node:assert/strict';
import {VoicePlayer} from '../.runtime/frontend-test/voice.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
function setup(load){const handles=[],states=[];let errors=0;const voice=new VoicePlayer({load,audio(){const h={plays:0,pauses:0,disposed:0,play:async()=>{h.plays++},pause:()=>h.pauses++,dispose:()=>h.disposed++,onEnded:f=>h.end=f};handles.push(h);return h},status:s=>states.push(s),unavailable:()=>errors++});return {voice,handles,states,errors:()=>errors}}
test('late voice after decision never creates or plays audio',async()=>{const pending=deferred();let signal;const s=setup((id,sig)=>{signal=sig;return pending.promise});const play=s.voice.speak('old');s.voice.stop();assert.equal(signal.aborted,true);pending.resolve(new Blob());await play;assert.equal(s.handles.length,0);assert.equal(s.states.at(-1),'Read aloud')});
test('old response cannot replace a newer character',async()=>{const old=deferred(),fresh=deferred();const s=setup(id=>id==='old'?old.promise:fresh.promise);const a=s.voice.speak('old'),b=s.voice.speak('new');fresh.resolve(new Blob());await b;old.resolve(new Blob());await a;assert.equal(s.handles.length,1);assert.equal(s.handles[0].plays,1);assert.equal(s.states.at(-1),'Speaking…')});
test('decision releases active audio immediately',async()=>{const s=setup(async()=>new Blob());await s.voice.speak('event');s.voice.stop();assert.equal(s.handles[0].pauses,1);assert.equal(s.handles[0].disposed,1)});
test('completion releases resources and offers replay',async()=>{const s=setup(async()=>new Blob());await s.voice.speak('event');s.handles[0].end();assert.equal(s.handles[0].disposed,1);assert.equal(s.states.at(-1),'Replay voice')});
test('unavailable voice leaves retry state',async()=>{const s=setup(async()=>{throw Error('offline')});await s.voice.speak('event');assert.equal(s.states.at(-1),'Retry voice');assert.equal(s.errors(),1)});
