"""The city, modelled instead of painted.

Every building in `public/art/iso` was generated by a diffusion model, and two
things about that never got fixed. The model paints signage nobody can read —
a marquee that says CIICATCE, a newspaper office that says NEWSAPWL — and it
paints a square of pavement under the building however firmly it is told not
to, which is the one thing a cut-out cannot have. Both were tried against
FLUX-schnell and FLUX-dev, with the ground stated as an exclusion and then as
a positive description, and both failed. A model that adds a sign when you
forbid one is not going to stop.

So the geometry is built here rather than asked for. An orthographic camera
cannot drift off the projection, a transparent film cannot render a pavement
that was never modelled, and a facade with no sign on it has no sign on it.
What the model was actually good at — texture, weathering, the look of painted
brick — is still worth asking for, and belongs on these surfaces as materials.

Runs headless through the `bpy` module, so there is no Blender application to
install and nothing outside the project's own toolchain:

    mise run city-art
"""
import math
import os
import sys

import bpy
from mathutils import Euler, Vector

# ---------------------------------------------------------------------------
# The projection.
#
# src/iso.ts draws the city with TILE = {w: 108, h: 54}: a plan tile is exactly
# twice as wide on screen as it is tall. That is a 2:1 dimetric projection, and
# it comes from a camera 30 degrees above the horizon looking down a 45 degree
# diagonal. Blender measures the camera's X rotation from straight down, so 30
# degrees of elevation is 60 degrees of rotation.
#
# This is the whole reason for doing it this way: the angle is a number, it is
# the same number for every building, and no amount of re-rendering can move it.

PITCH = math.radians(60)      # 30 degrees above the horizon => 2:1 on screen
YAW = math.radians(45)        # looking down the diagonal of the plan grid

# One plan tile (one BLOCK unit in iso.ts) in Blender units.
TILE = 1.0

# How much plan the frame holds. A building is at most about 1.6 tiles across
# its base, and the frame has to hold its height as well, so this is generous.
FRAME = 4.2

SIZE = 1024                   # square, so the cut-out carries its own footprint


def clear() -> None:
    """An empty world. bpy starts with a cube, a light and a camera in it."""
    bpy.ops.wm.read_factory_settings(use_empty=True)


def camera() -> None:
    """The orthographic camera, and the film that makes a cut-out possible.

    Film transparency is the point. There is no background to knock out and no
    flood fill that can eat into a dark facade, because the alpha channel is
    real. tools/isometric.py needed knock_out() and a holed() check precisely
    because a painted image has no alpha.

    Where the camera *stands* is worked out afterwards, by frame(), once there
    is something to look at.
    """
    cam_data = bpy.data.cameras.new("iso")
    cam_data.type = "ORTHO"
    cam = bpy.data.objects.new("iso", cam_data)
    bpy.context.scene.collection.objects.link(cam)
    cam.rotation_euler = (PITCH, 0, YAW)
    bpy.context.scene.camera = cam

    scene = bpy.context.scene
    scene.render.engine = "BLENDER_EEVEE"
    scene.render.resolution_x = SIZE
    scene.render.resolution_y = SIZE
    scene.render.film_transparent = True
    scene.render.image_settings.file_format = "PNG"
    scene.render.image_settings.color_mode = "RGBA"


# The camera's own axes, from the two angles above. Fixed for the whole city,
# which is the entire point of doing it this way.
def _basis():
    d = Vector((0, 0, -1))
    d.rotate(Euler((PITCH, 0, YAW)))
    right = d.cross(Vector((0, 0, 1)))
    right.normalize()
    return d.normalized(), right, right.cross(d.normalized()).normalized()


def frame(margin: float = 1.08) -> None:
    """Point the camera at what was built and fit the frame to it.

    Every building comes out centred and at the same scale for its size, which
    is what the drawn city needs: src/CityIso.tsx scales a sprite to the plot
    it stands on, so a cut-out that is off-centre in its own frame stands
    off-centre on its own ground.
    """
    look, right, up = _basis()
    points = [ob.matrix_world @ Vector(c)
              for ob in bpy.context.scene.objects if ob.type == "MESH"
              for c in ob.bound_box]
    us = [p.dot(right) for p in points]
    vs = [p.dot(up) for p in points]
    centre_u, centre_v = (min(us) + max(us)) / 2, (min(vs) + max(vs)) / 2

    cam = bpy.context.scene.camera
    cam.data.ortho_scale = max(max(us) - min(us), max(vs) - min(vs)) * margin
    # Sit back along the view direction, then slide sideways and up until the
    # model's projected centre is the frame's centre.
    middle = sum(points, Vector((0, 0, 0))) / len(points)
    cam.location = (middle - look * 14
                    + right * (centre_u - middle.dot(right))
                    + up * (centre_v - middle.dot(up)))


def light() -> None:
    """One sun, from one direction, for every building in the city.

    The generated art never managed this: each building was lit by whatever the
    model felt like, so the city was a collection of separately lit models. A
    sun is a direction, and it is the same direction for all twenty-two.
    """
    sun_data = bpy.data.lights.new("sun", type="SUN")
    sun_data.energy = 3.1
    sun_data.angle = math.radians(12)      # softens the shadow edge a little
    sun_data.color = (1.0, 0.94, 0.84)
    sun = bpy.data.objects.new("sun", sun_data)
    bpy.context.scene.collection.objects.link(sun)
    sun.rotation_euler = (math.radians(52), 0, math.radians(-25))

    # A dim sky so the shadowed faces are not black. The city's own night
    # lighting is applied in the view; this is the overcast daylight the art is
    # painted in, matching the LOOK string the diffusion prompts used.
    world = bpy.data.worlds.new("sky")
    world.use_nodes = True
    bg = world.node_tree.nodes["Background"]
    bg.inputs[0].default_value = (0.30, 0.32, 0.35, 1)
    bg.inputs[1].default_value = 0.65
    bpy.context.scene.world = world


# ---------------------------------------------------------------------------
# Materials.
#
# Flat colours with a little roughness variation, which is all a building at
# this size needs. This is the seam where generated art still belongs: a
# diffusion model is good at a tiling brick texture and bad at a building, so
# an image texture can be dropped onto these later without touching the
# geometry.

def surface(name: str, rgb: tuple[float, float, float], rough: float = 0.85,
            emit: tuple[float, float, float] | None = None):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = (*rgb, 1)
    bsdf.inputs["Roughness"].default_value = rough
    if emit is not None:
        bsdf.inputs["Emission Color"].default_value = (*emit, 1)
        bsdf.inputs["Emission Strength"].default_value = 1.15
    return mat


def block(name: str, at: tuple[float, float, float], size: tuple[float, float, float], mat):
    """One box. Every building here is a small pile of these."""
    bpy.ops.mesh.primitive_cube_add(size=1, location=(at[0], at[1], at[2] + size[2] / 2))
    ob = bpy.context.active_object
    ob.name = name
    ob.scale = (size[0], size[1], size[2])
    bpy.ops.object.transform_apply(scale=True)
    ob.data.materials.append(mat)
    return ob


# ---------------------------------------------------------------------------
# A building.
#
# Not one model: a recipe. Storeys, footprint and trim are arguments, so the
# twelve addresses and the fillers are the same code with different numbers —
# which is what makes them look like one city rather than twenty-two
# commissions. This is the part a diffusion model cannot do at all.

def tenement(width: float, depth: float, storeys: int, *, palette: dict,
             shopfront: bool = True, parapet: bool = True, cornice: bool = True,
             chimney: bool = True, lit: float = 0.55) -> None:
    storey = 0.42                      # one floor, in Blender units
    ground = 0.52 if shopfront else storey
    height = ground + storey * (storeys - 1)

    wall = surface("wall", palette["wall"], 0.9)
    upper = surface("upper", tuple(c * 1.14 for c in palette["wall"]), 0.9)
    trim = surface("trim", palette["trim"], 0.7)
    roof = surface("roof", palette["roof"], 0.95)
    glass = surface("glass", (0.055, 0.065, 0.075), 0.25)
    warm = surface("warm", palette["glow"], 0.4, emit=palette["glow"])

    # The shell, in two tones: the ground floor is rendered or painted and the
    # storeys above it are the brick. One flat colour top to bottom is what
    # makes a model read as a box.
    block("shell", (0, 0, 0), (width, depth, height), upper)
    block("base", (0, 0, 0), (width * 1.004, depth * 1.004, ground),
          surface("stall", palette["stall"], 0.8))

    # The shopfront: panes between piers, with a blank fascia over them. The
    # fascia is deliberately empty — the sign belongs to the renderer, which
    # knows what the place is actually called, rather than to a model that
    # cannot spell.
    if shopfront:
        panes, fascia = 3, 0.09
        sill, top = 0.09, ground - fascia - 0.05
        for i in range(panes):
            span = width / panes
            x = -width / 2 + span * (i + 0.5)
            block(f"pane-x-{i}", (x, -depth / 2, sill),
                  (span * 0.74, 0.03, top - sill), warm)
            span_d = depth / panes
            y = -depth / 2 + span_d * (i + 0.5)
            block(f"pane-y-{i}", (width / 2, y, sill),
                  (0.03, span_d * 0.74, top - sill), warm)
        block("fascia-x", (0, -depth / 2, ground - fascia),
              (width * 1.02, 0.035, fascia), trim)
        block("fascia-y", (width / 2, 0, ground - fascia),
              (0.035, depth * 1.02, fascia), trim)
        block("plinth", (0, 0, 0), (width * 1.02, depth * 1.02, sill), trim)

    # Windows, storey by storey, on both visible faces, each with a sill and a
    # lintel. Lit from a fixed sequence, so the same building is always lit the
    # same way and the city does not flicker between builds.
    seq = [0.71, 0.19, 0.94, 0.42, 0.08, 0.63, 0.87, 0.31, 0.55, 0.12, 0.77, 0.26]
    n = 0
    across = max(2, round(width / 0.30))
    deep = max(2, round(depth / 0.30))
    for s_i in range(1, storeys):
        z = ground + storey * (s_i - 1) + storey * 0.24
        tall = storey * 0.52
        for i in range(across):
            w = width / across
            x = -width / 2 + w * (i + 0.5)
            on = seq[n % len(seq)] < lit
            n += 1
            block(f"win-x-{s_i}-{i}", (x, -depth / 2, z), (w * 0.42, 0.03, tall),
                  warm if on else glass)
            block(f"sill-x-{s_i}-{i}", (x, -depth / 2, z - 0.022),
                  (w * 0.54, 0.045, 0.022), trim)
            block(f"lint-x-{s_i}-{i}", (x, -depth / 2, z + tall),
                  (w * 0.54, 0.045, 0.02), trim)
        for i in range(deep):
            d = depth / deep
            y = -depth / 2 + d * (i + 0.5)
            on = seq[n % len(seq)] < lit
            n += 1
            block(f"win-y-{s_i}-{i}", (width / 2, y, z), (0.03, d * 0.42, tall),
                  warm if on else glass)
            block(f"sill-y-{s_i}-{i}", (width / 2, y, z - 0.022),
                  (0.045, d * 0.54, 0.022), trim)
            block(f"lint-y-{s_i}-{i}", (width / 2, y, z + tall),
                  (0.045, d * 0.54, 0.02), trim)

    # The roof, and the trim that stops the box being a box. A cornice that
    # oversails is most of what makes a facade read as period rather than as a
    # cube with holes in it.
    block("roof", (0, 0, height), (width * 0.99, depth * 0.99, 0.012), roof)
    if cornice:
        block("cornice", (0, 0, height - 0.05), (width * 1.07, depth * 1.07, 0.03), trim)
        block("frieze", (0, 0, height - 0.085), (width * 1.03, depth * 1.03, 0.035), upper)
    if parapet:
        for dx, dy, w, d in ((0, -depth / 2, width * 1.02, 0.035),
                             (width / 2, 0, 0.035, depth * 1.02),
                             (0, depth / 2, width * 1.02, 0.035),
                             (-width / 2, 0, 0.035, depth * 1.02)):
            block("parapet", (dx, dy, height), (w, d, 0.075), trim)
        block("coping", (0, 0, height + 0.075), (width * 1.04, depth * 1.04, 0.014), roof)
    if chimney:
        block("chimney", (width * 0.2, depth * 0.22, height), (0.1, 0.1, 0.26),
              surface("stack", palette["stack"], 0.95))
        block("pot", (width * 0.2, depth * 0.22, height + 0.26), (0.115, 0.115, 0.03), trim)


def render(path: str) -> None:
    bpy.context.scene.render.filepath = path
    bpy.ops.render.render(write_still=True)


# ---------------------------------------------------------------------------
# The city's buildings, as numbers.
#
# The same twelve addresses and six fillers tools/isometric.py asks a model
# for, described as dimensions instead of adjectives. A tenement is not a
# different kind of thing from a nightclub here; it is taller and plainer.

BRICK = {"wall": (0.30, 0.19, 0.15), "trim": (0.36, 0.32, 0.27),
         "roof": (0.20, 0.21, 0.20), "stall": (0.16, 0.10, 0.09),
         "stack": (0.26, 0.15, 0.12), "glow": (1.0, 0.68, 0.30)}
STONE = {"wall": (0.42, 0.40, 0.34), "trim": (0.52, 0.50, 0.44),
         "roof": (0.22, 0.23, 0.23), "stall": (0.24, 0.22, 0.19),
         "stack": (0.34, 0.31, 0.27), "glow": (1.0, 0.72, 0.36)}
OLIVE = {"wall": (0.27, 0.28, 0.22), "trim": (0.38, 0.38, 0.31),
         "roof": (0.19, 0.20, 0.19), "stall": (0.15, 0.16, 0.13),
         "stack": (0.24, 0.23, 0.19), "glow": (1.0, 0.70, 0.33)}

PLACES: dict[str, dict] = {
    # The three the diffusion models were tested on, so the comparison is like
    # for like.
    "bar":     dict(width=1.05, depth=1.05, storeys=2, palette=BRICK, lit=0.8),
    "club":    dict(width=1.20, depth=1.15, storeys=2, palette=STONE, lit=0.7),
    "room":    dict(width=0.85, depth=1.10, storeys=4, palette=BRICK, lit=0.45),
    # And a filler, to show the same recipe making an ordinary building.
    "fill-a":  dict(width=1.00, depth=1.00, storeys=3, palette=OLIVE, lit=0.35),
}


def build(name: str, out_dir: str) -> str:
    spec = dict(PLACES[name])
    clear()
    camera()
    light()
    tenement(**spec)
    frame()
    path = os.path.join(out_dir, f"iso-{name}-v2.png")
    render(path)
    return path


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "public/art/iso"
    only = sys.argv[2:] or list(PLACES)
    os.makedirs(out, exist_ok=True)
    for place in only:
        print("building", place, flush=True)
        print("  ->", build(place, out), flush=True)
