import {useCallback,useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CityScene} from './CityScene';
import {TravelPresentation, type Journey} from './TravelPresentation';
import {icon,portrait,building} from './art';
import type {Snapshot,Command,Action,Place} from './types';
import './style.css';
const money=(n:number)=>'$'+Math.floor(n).toLocaleString();const time=(m:number)=>`Day ${Math.floor(m/1440)+1} · ${String(Math.floor(m%1440/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
function Icon({id}:{id:string}){return <span aria-hidden="true" dangerouslySetInnerHTML={{__html:icon(id)}}/>}
function Portrait({id}:{id:string}){return <span aria-hidden="true" dangerouslySetInnerHTML={{__html:portrait(id)}}/>}
class RequestError extends Error{constructor(message:string,public status:number){super(message)}}
async function api<T>(path:string,payload?:unknown):Promise<T>{const r=await fetch('/api/'+path,payload!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{});const data=await r.json();if(!r.ok)throw new RequestError(data.error||'Request failed',r.status);return data}
function App(){
 const [world,setWorld]=useState<Snapshot|null>(null),[tab,setTab]=useState('city'),[selected,setSelected]=useState('bar'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[voice,setVoice]=useState(localStorage.getItem('black-ledger-voice')==='yes'),[speech,setSpeech]=useState('Read aloud'),[error,setError]=useState('');
 const [journey,setJourney]=useState<Journey|null>(null);
 const audio=useRef<HTMLAudioElement|null>(null),voiceAbort=useRef<AbortController|null>(null),epoch=useRef(0),scene=useRef<HTMLElement|null>(null),latest=useRef(world),busyRef=useRef(false);latest.current=world;
 const stopVoice=useCallback(()=>{epoch.current++;voiceAbort.current?.abort();voiceAbort.current=null;if(audio.current){audio.current.pause();URL.revokeObjectURL(audio.current.src);audio.current=null}setSpeech('Read aloud')},[]);
 const speak=useCallback(async()=>{let e=latest.current?.event;if(!e)return;stopVoice();const token=epoch.current,abort=new AbortController();voiceAbort.current=abort;setSpeech('Preparing voice…');try{const r=await fetch('/api/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event:e.id}),signal:abort.signal});if(!r.ok)throw Error('Voice unavailable');const blob=await r.blob();if(token!==epoch.current||latest.current?.event?.id!==e.id)return;const player=new Audio(URL.createObjectURL(blob));audio.current=player;player.onended=()=>setSpeech('Replay voice');await player.play();if(token!==epoch.current){player.pause();return}setSpeech('Speaking…')}catch(err){if(token===epoch.current&&(err as Error).name!=='AbortError'){setSpeech('Retry voice');setNotice('Voice is unavailable. You can continue reading.')}}},[stopVoice]);
 useEffect(()=>{let canceled=false;async function boot(){try{const pending=localStorage.getItem('black-ledger-pending');if(pending){try{await api('action',JSON.parse(pending));localStorage.removeItem('black-ledger-pending')}catch(err){if(err instanceof RequestError&&[400,409].includes(err.status))localStorage.removeItem('black-ledger-pending');else throw err}}const w=await api<Snapshot>('state');if(!canceled)setWorld(w)}catch(err){setError((err as Error).message)}}boot();return()=>{canceled=true;stopVoice()}},[stopVoice]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id)},[notice]);
 useEffect(()=>{if(world&&!world.player.alive)scene.current?.querySelector<HTMLButtonElement>('button')?.focus()},[world?.player.alive]);
 useEffect(()=>{stopVoice();if(world?.event){scene.current?.querySelector<HTMLButtonElement>('button[data-choice]')?.focus();if(voice)speak()}},[world?.event?.id,stopVoice,speak]);
 useEffect(()=>{const id=setInterval(async()=>{if(busyRef.current||latest.current?.director.status!=='writing')return;try{const next=await api<Snapshot>('state');setWorld(w=>w&&w.revision===next.revision?{...w,director:next.director}:w)}catch{}},3000);return()=>clearInterval(id)},[]);
 async function prepare(){try{await api('director',{});setWorld(await api<Snapshot>('state'))}catch(err){setNotice((err as Error).message)}}
 async function commit(command:Command){if(!world||busyRef.current||journey)return;stopVoice();busyRef.current=true;setBusy(true);try{const pending=localStorage.getItem('black-ledger-pending');if(pending){await api('action',JSON.parse(pending));localStorage.removeItem('black-ledger-pending');setWorld(await api<Snapshot>('state'));setNotice('Recovered your previous action. Please choose your next action again.');return}
 const payload={...command,request_id:crypto.randomUUID(),revision:world.revision};localStorage.setItem('black-ledger-pending',JSON.stringify(payload));const next=await api<Snapshot>('action',payload);localStorage.removeItem('black-ledger-pending');setWorld(next);if(command.kind==='travel'&&!next.event&&next.player.alive&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const from=world.locations.find(l=>l.id===world.player.location),to=next.locations.find(l=>l.id===next.player.location);if(from&&to&&from.id!==to.id)setJourney({from,to,minutes:next.last_result?.elapsed||0})}if(command.kind==='new_life')setSelected('bar');if(!next.event)setNotice(next.last_result?.records.at(-1)?.title||'Saved');if(next.player.job_count>=2&&!['writing','ready'].includes(next.director.status)&&next.minute-next.director.last_request>180){await api('director',{});setWorld(await api<Snapshot>('state'))}
 }catch(err){if(err instanceof RequestError&&[400,409].includes(err.status))localStorage.removeItem('black-ledger-pending');setNotice((err as Error).message);try{setWorld(await api<Snapshot>('state'))}catch{}}finally{busyRef.current=false;setBusy(false)}}
 function toggleVoice(){const enabled=!voice;setVoice(enabled);localStorage.setItem('black-ledger-voice',enabled?'yes':'no');if(enabled)speak();else stopVoice()}
 if(!world)return <div className="loading">BLACK LEDGER<span>{error||'Opening the books…'}</span>{error&&<button onClick={()=>location.reload()}>Reconnect</button>}</div>;
 const p=world.player,locationInfo=world.locations.find(l=>l.id===selected)||world.locations[0],event=world.event,npc=world.npcs.find(n=>n.id===event?.speaker)||world.npcs[0];
 function actionButton(a:Action){return <button key={a.id} className={`action ${a.id==='provoke'?'danger':a.id==='travel'?'primary':''}`} disabled={a.disabled||busy||!!journey} onClick={()=>commit({kind:a.id,target:a.target})}><strong>{a.label}{a.id==='travel'?' ↗':''}</strong><span className="meta">{a.minutes?`${a.minutes} min`:''}{a.cost>0&&<span>{money(a.cost)}</span>}</span><span className="desc">{a.reason||a.detail}</span></button>}
 function propertyPanel(l:Place){return <aside className="sidebar"><div className="person"><Portrait id={p.name}/><div><b>{p.name}</b><small>{p.respect<6?'An unknown face':p.crew.length?'Crew leader':'Neighborhood operator'} · Life {world!.life}</small><div className="bar"><i style={{width:`${p.health}%`}}/></div></div></div><div className="eyebrow">{l.locked?'BEYOND YOUR REACH':l.id===p.location?'YOU ARE HERE':'NEIGHBORHOOD DIRECTORY'} / {['Old Harbor','Ashbury','The Heights'][l.district]}</div><h2>{l.name}</h2><p className="subtle">{l.blurb}</p><div className="building-art"><svg viewBox="0 0 210 130" aria-hidden="true" dangerouslySetInnerHTML={{__html:building(l,true)}}/></div><div className="fact-grid"><div><span>Ownership</span><b>{l.owned?'Your organization':l.owner==='bellandi'?'Bellandi Family':l.owner.startsWith('former:')?l.owner.slice(7)+'’s survivors':'Independent'}</b></div><div><span>{l.owned?'Hourly income':'Condition'}</span><b>{l.owned?money(l.income*l.condition/100):l.condition+'%'}</b></div></div><div className="actions">{l.actions.map(actionButton)}</div><div className="bottom-note"><Icon id="clock"/> Decisions pause the clock. Commitments advance it.</div></aside>}
 function content(){const w=world!;if(tab==='city'){const last=[...w.history].reverse().find(r=>r.kind!=='travel')||w.history.at(-1)!;return <div className="workspace"><section className="city-pane"><div className="map-heading"><div className="eyebrow">THE CITY OF</div><h1>Bellwether</h1><p>A place to make your name. Or lose it.</p><div className="chapter-chip">{p.respect<6?'I · A FOOT IN THE DOOR':p.crew.length?'II · SOMETHING OF YOUR OWN':'I · MAKING CONNECTIONS'}</div></div><div className="map-key"><i/>Your position<i className="enemy"/>Rival interests</div><div className="city-stage"><CityScene state={w} selected={selected} onSelect={setSelected} hideMarker={!!journey}/>{journey&&<TravelPresentation journey={journey} onDone={()=>setJourney(null)}/>}</div><div className="ticker"><Icon id="news"/><div><b>{last.title}</b><p>{last.text}</p></div></div></section>{propertyPanel(locationInfo)}</div>}
 if(tab==='ledger')return <section className="section-content"><div className="eyebrow">ACCOUNTS & CONSEQUENCES</div><h1 className="screen-title">The ledger</h1><div className="fact-grid"><div><span>Business income</span><b>{money(w.income)}/hour</b></div><div><span>Housing, security & wages</span><b>{money(w.daily_cost)}/day</b></div></div><p className="subtle">Income and expenses advance with game time. The city remembers previous lives.</p><div className="log">{[...w.history].reverse().map(r=><article key={r.id} className={'log-row '+r.kind}><time>{time(r.minute)}<br/>Life {r.life}</time><div><h3>{r.title}</h3><p>{r.text}</p></div></article>)}</div></section>;
 if(tab==='crew')return <section className="section-content"><div className="eyebrow">PEOPLE ARE YOUR EMPIRE</div><h1 className="screen-title">Names worth knowing</h1><p className="subtle">Your crew is small. Every relationship begins somewhere.</p><div className="cards">{w.npcs.map(n=><article className="card" key={n.id}><div className="person"><Portrait id={n.id}/><div><b>{n.name}</b><small>{n.role}</small></div></div><p>Trust {n.trust} · {p.crew.some(c=>c.id===n.id)?'In your crew':'Independent contact'}</p>{n.id==='leo'&&p.crew.length>0&&<><p>Loyalty {p.crew[0].loyalty}/100 · $12/day</p><p>{w.tasks.length?`On collections · due ${time(w.tasks[0].due)}`:'Available for an assignment'}</p></>}{n.id==='mara'&&<p>Information network {p.contacts}/5. Stronger contacts may warn you of danger.</p>}</article>)}</div></section>;
 if(tab==='families')return <section className="section-content"><div className="eyebrow">POWER WAS HERE BEFORE YOU</div><h1 className="screen-title">The other families</h1><p className="subtle">The city does not scale its dangers to your experience. Some doors are better left unopened.</p><div className="cards">{w.factions.map(f=><article className="card" key={f.id}><Icon id="families"/><h2>{f.name}</h2><p>Led by {f.leader}</p><div className="fact-grid"><div><span>Power</span><b>{f.power}/100</b></div><div><span>Your standing</span><b className={f.goodwill<0?'warning':''}>{f.goodwill>0?'+':''}{f.goodwill}</b></div></div><p>{f.goodwill<-20?'Your actions have made this family hostile. What they intend to do is not necessarily known to you.':'A relationship waiting to take shape. Reputation is not the same as protection.'}</p></article>)}</div><h2 style={{marginTop:32}}>The city you inherited</h2>{w.dead.length?w.dead.map((d,i)=><p className="subtle" key={i}>{d.name} died on {time(d.minute)}. {d.cause}</p>):<p className="subtle">No previous lives. What happens next will leave a mark.</p>}</section>;
 if(tab==='settings')return <section className="section-content"><div className="eyebrow">BEHIND THE CURTAIN</div><h1 className="screen-title">The storyteller</h1><div className="card" style={{maxWidth:650}}><h3><span className="status-dot"/>{w.director.status==='writing'?'Preparing an encounter':w.director.status==='ready'?'An encounter is ready':'Local director'}</h3><p>{w.director.detail}</p><button className="plain" onClick={prepare} disabled={w.director.status==='writing'}>Prepare another encounter</button><p>Model output proposes bounded opportunities. The Go simulation owns money, time, injuries, property, and death. Authored incidents remain playable if the local model is unavailable.</p></div><div className="card" style={{maxWidth:650,marginTop:20}}><h3>Voice acting</h3><p>Named characters retain their assigned voice. Decisions cancel speech, including audio that is still being generated.</p><button className="plain" onClick={toggleVoice}>{voice?'Disable':'Enable'} voices</button></div><p className="subtle">Ironman · saved locally after each action. No clock advances while this page is open.</p></section>;
 return <section className="section-content help"><div className="eyebrow">YOUR FIRST DAYS</div><h1 className="screen-title">Become someone who matters.</h1><p>You arrived with $90, a rented room, and one contact. Begin at Saint Agnes, earn Mara’s trust, and build a reliable income before challenging the city’s established families.</p><ol><li><b>Visit Saint Agnes.</b> Select it on the map, then Visit. Carry envelopes for $45 and respect.</li><li><b>Build relationships.</b> Buy Mara coffee to develop your warning network. Recruit Leo after earning 6 respect.</li><li><b>Establish a foothold.</b> The Bluebird Laundry requires $180 and 6 respect. It pays automatically as time passes.</li><li><b>Manage your exposure.</b> Housing and guards matter. Rest restores health, but rivals can act while you sleep.</li><li><b>Expand.</b> Earn 10 respect and invest $100 in contacts across town to access Ashbury.</li></ol><h2>Hard rules</h2><p>The clock only advances when you commit to an action. Inspecting, reading, and AI preparation take no game time. Animations only present committed outcomes.</p><p>Threats are not always announced. Bellandi’s casino is protected from the start. Provoking it can get you killed, even in your first day.</p><p>Death is permanent. Start as a new stranger in this city. Your old organization becomes independent; its assets are not automatically yours.</p><h2>Prototype scope</h2><p>This first neighborhood uses authored progression and retaliation plus optional locally generated opportunities. Broader autonomous family politics and more incident types follow once this loop is proven.</p></section>
 }
 return <><div className={'shell '+(busy?'busy':'')} inert={!!event||!p.alive}><nav className="rail" aria-label="Main navigation"><div className="monogram"><span>B</span></div>{[['city','City'],['crew','People'],['families','Families'],['ledger','Ledger'],['help','Guide']].map(([id,label])=><button key={id} className={tab===id?'active':''} aria-label={label} onClick={()=>setTab(id)}><Icon id={id}/>{label}</button>)}<button className="bottom" onClick={toggleVoice} aria-label={(voice?'Disable':'Enable')+' voice acting'}><Icon id={voice?'voice':'mute'}/>Voice {voice?'on':'off'}</button><button onClick={()=>setTab('settings')} aria-label="Settings"><Icon id="settings"/>Settings</button></nav><main className="page"><header className="topbar"><div><div className="eyebrow">A CITY REMEMBERS</div><div className="brand">BLACK LEDGER</div></div><div className="stats">{[['cash',money(p.cash),'Cash on hand'],['respect',p.respect,'Respect'],['health',p.health,'Health'],['heat',p.heat,'Heat']].map(([id,value,label])=><div className="stat" key={id}><Icon id={String(id)}/><b>{value}</b><small>{label}</small></div>)}<div className="stat clock"><b>{time(world.minute)}</b><small>{busy?'Resolving…':'Clock paused · awaiting your action'}</small></div></div></header>{content()}</main></div>
 {(event||!p.alive)&&<div className="modal-shade"><section ref={scene} className="scene" role="dialog" aria-modal="true" aria-labelledby="scene-title" onKeyDown={e=>{if(e.key==='Escape')stopVoice();if(e.key==='Tab'){const buttons=[...scene.current!.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')];if(!buttons.length)return;const first=buttons[0],last=buttons.at(-1)!;if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}}}>
 {!p.alive?<><div className="eyebrow">THE CITY CONTINUES</div><div className="death-seal">✦</div><h2 id="scene-title">{p.name} is dead.</h2><p className="spoken">{world.dead.at(-1)?.cause}</p><p className="subtle">Your properties pass to your former organization. Another life begins without your money, rank, or authority. The history remains.</p><button className="action primary" disabled={busy} onClick={()=>commit({kind:'new_life'})}>Begin as a new person <Icon id="arrow"/></button><p className="source">Life {world.life} · {time(world.minute)} · Outcome committed</p></>:event&&<><div className="eyebrow"><span>{event.kind==='attack'?'A MOMENT TO ACT':'A PRIVATE CONVERSATION'}</span><span>TIME PAUSED</span></div><h2 id="scene-title">{event.title}</h2><div className="person"><Portrait id={npc.id}/><div><b>{npc.name}</b><small>{npc.role}</small></div></div><p className="spoken">{event.body}</p><div className="speech-control"><button className="plain" onClick={speak}><Icon id="voice"/> {speech}</button><button className="plain" onClick={stopVoice}>Stop voice</button></div><div className="choices">{event.choices.map((c,i)=><button key={c.id} data-choice className="action" disabled={c.disabled||busy} onClick={()=>commit({kind:'choice',choice:c.id,event:event.id})}><span className="number">0{i+1}</span><span><strong>{c.label}</strong><span className="desc">{c.detail}{c.disabled?' · Not enough cash':''}</span></span></button>)}</div><p className="source">{event.source==='local-ai'?'Local AI encounter':'City encounter'} · Decisions are saved immediately.</p></>}
 </section></div>}{notice&&<div id="toast" role="status" aria-live="polite" style={{display:'block'}}>{notice}</div>}</>
}
createRoot(document.getElementById('root')!).render(<App/>);
