// The city makes a noise when something happens in it.
//
// These are synthesised rather than sampled: a gunshot is a noise burst with a
// hard envelope, an explosion is low noise with a long tail, a police lamp is
// two tones alternating. Nothing is downloaded, nothing is licensed, nothing
// has to be generated by a model that cannot be relied on for audio — and the
// whole file is a few hundred bytes rather than a few megabytes.
//
// It is also the honest match for the art: a 1950s city heard through a
// newsreel, not a field recording.

let context: AudioContext | null = null;

const sceneSounds = new Set<() => void>();
class SceneSound {
  private voices = new Set<() => void>();
  constructor() { sceneSounds.add(this.cancel); }
  add(stop: () => void) { this.voices.add(stop); }
  release(stop: () => void) {
    this.voices.delete(stop);
    if (!this.voices.size) sceneSounds.delete(this.cancel);
  }
  cancel = () => {
    for (const stop of [...this.voices]) stop();
    sceneSounds.delete(this.cancel);
  };
}

function startVoice(source: AudioScheduledSourceNode, nodes: AudioNode[], at: number, end: number, scene?: SceneSound) {
  let finished = false;
  const cleanup = () => {
    if (finished) return;
    finished = true;
    source.disconnect();
    nodes.forEach(node => node.disconnect());
    scene?.release(stop);
  };
  const stop = () => {
    if (finished) return;
    try { source.stop(); } catch { /* already ended or not started */ }
    cleanup();
  };
  source.onended = cleanup;
  scene?.add(stop);
  try {
    source.start(at);
    source.stop(end);
  } catch (error) {
    stop();
    throw error;
  }
  return stop;
}

// A browser will not let a page make a noise before somebody has touched it,
// so the context is built on the first sound and reused after that.
function audio(): AudioContext | null {
  if (context) return context;
  try {
    context = new (window.AudioContext || (window as any).webkitAudioContext)();
    return context;
  } catch {
    return null;
  }
}

export function soundOn(): boolean {
  try {
    return localStorage.getItem('black-ledger-sound') !== 'off';
  } catch {
    return true;
  }
}

export function setSound(on: boolean) {
  if (!on) for (const cancel of [...sceneSounds]) cancel();
  try {
    localStorage.setItem('black-ledger-sound', on ? 'on' : 'off');
  } catch {
    /* a private window */
  }
}

// noise is the raw material for anything that is not a tone: a shot, a blast,
// the crackle under a fire.
function noise(ctx: AudioContext, seconds: number): AudioBufferSourceNode {
  const frames = Math.max(1, Math.floor(ctx.sampleRate * seconds));
  const buffer = ctx.createBuffer(1, frames, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < frames; i++) data[i] = Math.random() * 2 - 1;
  const source = ctx.createBufferSource();
  source.buffer = buffer;
  return source;
}

// One shot: a crack with almost no attack and a short tail.
function shot(ctx: AudioContext, at: number, level = 0.5, scene?: SceneSound) {
  const source = noise(ctx, 0.3);
  const band = ctx.createBiquadFilter();
  band.type = 'bandpass';
  band.frequency.value = 1800;
  band.Q.value = 0.7;
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(0, at);
  gain.gain.linearRampToValueAtTime(level, at + 0.004);
  gain.gain.exponentialRampToValueAtTime(0.0001, at + 0.22);
  source.connect(band).connect(gain).connect(ctx.destination);
  return startVoice(source, [band, gain], at, at + 0.32, scene);
}

/** One visible city shot, cancellable on Skip, reduced motion or navigation. */
export function playCityGunshot(): (() => void) | undefined {
  if (!soundOn()) return;
  const ctx = audio();
  if (!ctx) return;
  try {
    if (ctx.state === 'suspended') ctx.resume().catch(() => {});
    return shot(ctx, ctx.currentTime + 0.02, 0.4);
  } catch {
    // Sound failure must never interrupt the city animation loop.
    return undefined;
  }
}

// A blast: low, long, and with a body you feel rather than hear.
function blast(ctx: AudioContext, at: number, scene: SceneSound) {
  const source = noise(ctx, 1.6);
  const low = ctx.createBiquadFilter();
  low.type = 'lowpass';
  low.frequency.setValueAtTime(900, at);
  low.frequency.exponentialRampToValueAtTime(90, at + 1.1);
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(0, at);
  gain.gain.linearRampToValueAtTime(0.7, at + 0.02);
  gain.gain.exponentialRampToValueAtTime(0.0001, at + 1.5);
  source.connect(low).connect(gain).connect(ctx.destination);
  startVoice(source, [low, gain], at, at + 1.6, scene);

  // The thump under it.
  const body = ctx.createOscillator();
  body.type = 'sine';
  body.frequency.setValueAtTime(78, at);
  body.frequency.exponentialRampToValueAtTime(26, at + 0.8);
  const thump = ctx.createGain();
  thump.gain.setValueAtTime(0.6, at);
  thump.gain.exponentialRampToValueAtTime(0.0001, at + 0.9);
  body.connect(thump).connect(ctx.destination);
  startVoice(body, [thump], at, at + 1, scene);
}

// Two tones, alternating: a car at the kerb with its lamp turning.
function siren(ctx: AudioContext, at: number, scene: SceneSound, times = 4) {
  for (let i = 0; i < times; i++) {
    const when = at + i * 0.42;
    const tone = ctx.createOscillator();
    tone.type = 'square';
    tone.frequency.setValueAtTime(i % 2 ? 460 : 610, when);
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, when);
    gain.gain.linearRampToValueAtTime(0.09, when + 0.05);
    gain.gain.setValueAtTime(0.09, when + 0.3);
    gain.gain.exponentialRampToValueAtTime(0.0001, when + 0.4);
    tone.connect(gain).connect(ctx.destination);
    startVoice(tone, [gain], when, when + 0.42, scene);
  }
}

// Something happened, and the city noticed: a dull knock, no drama.
function knock(ctx: AudioContext, at: number, scene: SceneSound) {
  const tone = ctx.createOscillator();
  tone.type = 'triangle';
  tone.frequency.setValueAtTime(220, at);
  tone.frequency.exponentialRampToValueAtTime(90, at + 0.18);
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(0.22, at);
  gain.gain.exponentialRampToValueAtTime(0.0001, at + 0.3);
  tone.connect(gain).connect(ctx.destination);
  startVoice(tone, [gain], at, at + 0.32, scene);
}

// What each kind of moment sounds like. The kinds are the core's own, from
// core/witness.go, and a kind nobody has scored still makes the knock rather
// than nothing — silence reads as a bug.
export function playMoment(kind: string) {
  if (!soundOn()) return;
  const ctx = audio();
  if (!ctx) return;
  const scene = new SceneSound();
  try {
    if (ctx.state === 'suspended') ctx.resume().catch(() => {});
    const at = ctx.currentTime + 0.02;
    switch (kind) {
      case 'explosion': blast(ctx, at, scene); break;
      case 'killing':
        shot(ctx, at, 0.55, scene);
        shot(ctx, at + 0.17, 0.4, scene);
        break;
      case 'gunfight':
        for (let i = 0; i < 5; i++)
          shot(ctx, at + i * 0.13 + Math.random() * 0.04, 0.3 + Math.random() * 0.2, scene);
        break;
      case 'raid':
      case 'arrest': siren(ctx, at, scene); break;
      default: knock(ctx, at, scene);
    }
    return scene.cancel;
  } catch {
    scene.cancel();
    return undefined;
  }
}

// The room, and the machines in it.
//
// "We should also add ambient sounds and sounds to the slot machines and
// whatnot." Same contract as the rest of this file: synthesised, nothing
// downloaded, nothing licensed. A handle is a spring and a clunk, a drum
// stopping is a wooden knock, and a payout is a run of coins into a metal tray.

// clunk is a mechanism doing something: the handle going over, a drum stopping.
function clunk(ctx: AudioContext, at: number, pitch: number, level = 0.3) {
  const tone = ctx.createOscillator();
  tone.type = 'triangle';
  tone.frequency.setValueAtTime(pitch, at);
  tone.frequency.exponentialRampToValueAtTime(pitch * 0.45, at + 0.09);
  const body = ctx.createGain();
  body.gain.setValueAtTime(level, at);
  body.gain.exponentialRampToValueAtTime(0.0001, at + 0.13);
  tone.connect(body).connect(ctx.destination);
  tone.start(at);
  tone.stop(at + 0.15);

  // The rattle of the thing it is attached to.
  const rattle = noise(ctx, 0.08);
  const band = ctx.createBiquadFilter();
  band.type = 'bandpass';
  band.frequency.value = pitch * 4;
  band.Q.value = 2;
  const edge = ctx.createGain();
  edge.gain.setValueAtTime(level * 0.5, at);
  edge.gain.exponentialRampToValueAtTime(0.0001, at + 0.07);
  rattle.connect(band).connect(edge).connect(ctx.destination);
  rattle.start(at);
  rattle.stop(at + 0.09);
}

// coin is one piece of metal landing on other metal.
function coin(ctx: AudioContext, at: number) {
  const tone = ctx.createOscillator();
  tone.type = 'square';
  tone.frequency.setValueAtTime(1800 + Math.random() * 900, at);
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(0, at);
  gain.gain.linearRampToValueAtTime(0.06, at + 0.003);
  gain.gain.exponentialRampToValueAtTime(0.0001, at + 0.12);
  tone.connect(gain).connect(ctx.destination);
  tone.start(at);
  tone.stop(at + 0.14);
}

// What each thing at the tables sounds like. Called by the interface at the
// moment the core says the thing happened, never on a timer of its own.
export function playTable(kind: string, count = 1) {
  if (!soundOn()) return;
  const ctx = audio();
  if (!ctx) return;
  if (ctx.state === 'suspended') ctx.resume().catch(() => {});
  const at = ctx.currentTime + 0.02;
  switch (kind) {
    case 'handle':
      clunk(ctx, at, 150, 0.35);
      clunk(ctx, at + 0.11, 110, 0.2);
      break;
    case 'reel':
      clunk(ctx, at, 320, 0.22);
      break;
    case 'coins':
      // Longer for a bigger win: the tray is how a machine tells the room.
      for (let i = 0; i < Math.max(4, Math.min(26, count)); i++)
        coin(ctx, at + i * 0.045 + Math.random() * 0.015);
      break;
    case 'card':
      clunk(ctx, at, 620, 0.12);
      break;
    // Chips going into the middle. Higher and drier than a coin in a tray,
    // because clay on baize is not brass on steel, and one for each rather
    // than one for the lot: a raise sounds like more money than a call.
    case 'chips':
      for (let i = 0; i < Math.max(1, Math.min(8, count)); i++)
        clunk(ctx, at + i * 0.055 + Math.random() * 0.02, 780 + Math.random() * 120, 0.09);
      break;
    case 'dice':
      for (let i = 0; i < 5; i++)
        clunk(ctx, at + i * 0.06 + Math.random() * 0.02, 420 + Math.random() * 200, 0.1);
      break;
    default:
      clunk(ctx, at, 240, 0.18);
  }
}

// The room itself: the hum of a busy floor under everything else. Started when
// the player sits down and stopped when they get up, because a noise that goes
// on after you have left the table is a noise nobody asked for.
let room: {gain: GainNode; nodes: AudioScheduledSourceNode[]} | null = null;

export function roomTone(on: boolean) {
  const ctx = audio();
  if (!ctx) return;
  if (!on || !soundOn()) {
    if (room) {
      const {gain, nodes} = room;
      room = null;
      gain.gain.setTargetAtTime(0, ctx.currentTime, 0.25);
      setTimeout(() => {
        nodes.forEach(n => {
          try {
            n.stop();
          } catch {
            /* already stopped */
          }
        });
      }, 900);
    }
    return;
  }
  if (room) return;
  if (ctx.state === 'suspended') ctx.resume().catch(() => {});
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(0, ctx.currentTime);
  gain.gain.setTargetAtTime(0.035, ctx.currentTime, 0.8);
  gain.connect(ctx.destination);

  // A room full of people is low broadband noise with the top taken off it.
  const hum = noise(ctx, 4);
  hum.loop = true;
  const soft = ctx.createBiquadFilter();
  soft.type = 'lowpass';
  soft.frequency.value = 620;
  soft.Q.value = 0.4;
  hum.connect(soft).connect(gain);
  hum.start();

  room = {gain, nodes: [hum]};
}
