// The city makes a noise when something happens in it.
//
// These are synthesised rather than sampled: a gunshot is a noise burst with a
// hard envelope, an explosion is low noise with a long tail, a police lamp is
// two tones alternating. Nothing is downloaded, nothing is licensed, nothing
// has to be generated by a model that cannot be relied on for audio — and the
// whole file is a few hundred bytes rather than a few megabytes.
//
// It is also the honest match for the art: a 1950s city heard through a
// newsreel, not a field recording.

let context: AudioContext | null = null;

// A browser will not let a page make a noise before somebody has touched it,
// so the context is built on the first sound and reused after that.
function audio(): AudioContext | null {
  if (context) return context;
  try {
    context = new (window.AudioContext || (window as any).webkitAudioContext)();
    return context;
  } catch {
    return null;
  }
}

export function soundOn(): boolean {
  try { return localStorage.getItem('black-ledger-sound') !== 'off' } catch { return true }
}

export function setSound(on: boolean) {
  try { localStorage.setItem('black-ledger-sound', on ? 'on' : 'off') } catch { /* a private window */ }
}

// noise is the raw material for anything that is not a tone: a shot, a blast,
// the crackle under a fire.
function noise(ctx: AudioContext, seconds: number): AudioBufferSourceNode {
  const frames = Math.max(1, Math.floor(ctx.sampleRate * seconds));
  const buffer = ctx.createBuffer(1, frames, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < frames; i++) data[i] = Math.random() * 2 - 1;
  const source = ctx.createBufferSource();
  source.buffer = buffer;
  return source;
}

// One shot: a crack with almost no attack and a short tail.
function shot(ctx: AudioContext, at: number, level = .5) {
  const source = noise(ctx, .3);
  const band = ctx.createBiquadFilter();
  band.type = 'bandpass'; band.frequency.value = 1800; band.Q.value = .7;
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(0, at);
  gain.gain.linearRampToValueAtTime(level, at + .004);
  gain.gain.exponentialRampToValueAtTime(.0001, at + .22);
  source.connect(band).connect(gain).connect(ctx.destination);
  source.start(at); source.stop(at + .32);
}

// A blast: low, long, and with a body you feel rather than hear.
function blast(ctx: AudioContext, at: number) {
  const source = noise(ctx, 1.6);
  const low = ctx.createBiquadFilter();
  low.type = 'lowpass';
  low.frequency.setValueAtTime(900, at);
  low.frequency.exponentialRampToValueAtTime(90, at + 1.1);
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(0, at);
  gain.gain.linearRampToValueAtTime(.7, at + .02);
  gain.gain.exponentialRampToValueAtTime(.0001, at + 1.5);
  source.connect(low).connect(gain).connect(ctx.destination);
  source.start(at); source.stop(at + 1.6);

  // The thump under it.
  const body = ctx.createOscillator();
  body.type = 'sine';
  body.frequency.setValueAtTime(78, at);
  body.frequency.exponentialRampToValueAtTime(26, at + .8);
  const thump = ctx.createGain();
  thump.gain.setValueAtTime(.6, at);
  thump.gain.exponentialRampToValueAtTime(.0001, at + .9);
  body.connect(thump).connect(ctx.destination);
  body.start(at); body.stop(at + 1);
}

// Two tones, alternating: a car at the kerb with its lamp turning.
function siren(ctx: AudioContext, at: number, times = 4) {
  for (let i = 0; i < times; i++) {
    const when = at + i * .42;
    const tone = ctx.createOscillator();
    tone.type = 'square';
    tone.frequency.setValueAtTime(i % 2 ? 460 : 610, when);
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, when);
    gain.gain.linearRampToValueAtTime(.09, when + .05);
    gain.gain.setValueAtTime(.09, when + .3);
    gain.gain.exponentialRampToValueAtTime(.0001, when + .4);
    tone.connect(gain).connect(ctx.destination);
    tone.start(when); tone.stop(when + .42);
  }
}

// Something happened, and the city noticed: a dull knock, no drama.
function knock(ctx: AudioContext, at: number) {
  const tone = ctx.createOscillator();
  tone.type = 'triangle';
  tone.frequency.setValueAtTime(220, at);
  tone.frequency.exponentialRampToValueAtTime(90, at + .18);
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(.22, at);
  gain.gain.exponentialRampToValueAtTime(.0001, at + .3);
  tone.connect(gain).connect(ctx.destination);
  tone.start(at); tone.stop(at + .32);
}

// What each kind of moment sounds like. The kinds are the core's own, from
// core/witness.go, and a kind nobody has scored still makes the knock rather
// than nothing — silence reads as a bug.
export function playMoment(kind: string) {
  if (!soundOn()) return;
  const ctx = audio();
  if (!ctx) return;
  if (ctx.state === 'suspended') ctx.resume().catch(() => {});
  const at = ctx.currentTime + .02;
  switch (kind) {
    case 'explosion':
      blast(ctx, at);
      break;
    case 'killing':
      shot(ctx, at, .55); shot(ctx, at + .17, .4);
      break;
    case 'gunfight':
      for (let i = 0; i < 5; i++) shot(ctx, at + i * .13 + Math.random() * .04, .3 + Math.random() * .2);
      break;
    case 'raid':
    case 'arrest':
      siren(ctx, at);
      break;
    default:
      knock(ctx, at);
  }
}
