import type {VisualCue} from './types';
import {useEffect,useRef,useState} from 'react';
import type {Journey} from './TravelPresentation';
import {paintedBuildings,paintedLocations} from './cityAssets';
interface Props {onDirectory:()=>void;sequence:VisualCue|null;properties:{id:string;condition:number}[];selected:string;minute:number;position:string;journey:Journey|null;onSelect:(id:string)=>void}
/** Isolated presentation adapter. Only whitelisted inspection messages cross this boundary. */
export function StreetScene({properties,selected,minute,position,journey,sequence,onSelect,onDirectory}:Props){
 const [artState,setArtState]=useState<'loading'|'ready'|'failed'>('loading'),[attempt,setAttempt]=useState(0);
 useEffect(()=>{setArtState('loading');const timer=setTimeout(()=>setArtState(s=>s==='loading'?'failed':s),12000);return()=>clearTimeout(timer)},[attempt]);
 const [motion,setMotion]=useState(localStorage.getItem('black-ledger-motion')!=='off');
 const frame=useRef<HTMLIFrameElement>(null),latest=useRef({properties,selected,minute,position,journey,sequence,onSelect,motion});latest.current={properties,selected,minute,position,journey,sequence,onSelect,motion};
 function sync(){frame.current?.contentWindow?.postMessage({type:'blackledger:presentation',sequence:latest.current.sequence,properties:latest.current.properties.map(p=>({id:p.id,condition:p.condition})),selected:latest.current.selected,minute:latest.current.minute,motion:latest.current.motion,position:latest.current.position,journey:latest.current.journey?{from:latest.current.journey.from.id,to:latest.current.journey.to.id}:null},location.origin)}
 useEffect(()=>{const receive=(e:MessageEvent)=>{if(e.source!==frame.current?.contentWindow||e.origin!==location.origin)return;if(e.data?.type==='blackledger:ready'){setArtState('ready');sync()}if(e.data?.type==='blackledger:art-error')setArtState('failed');if(e.data?.type==='blackledger:inspect'&&paintedLocations.includes(e.data.location))latest.current.onSelect(e.data.location)};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[]);
 useEffect(sync,[properties,selected,minute,motion,position,journey,sequence]);
 return <div className="street-scene"><iframe key={attempt} ref={frame} title="Old Harbor illustrated street" src="/street-study.html?embed=1" onLoad={sync}/>{artState!=='ready'&&<div className="street-load-state" role="status"><strong>{artState==='failed'?'The street illustration is unavailable':'Opening Old Harbor…'}</strong><p>{artState==='failed'?'You can keep playing through the address book. Your campaign is saved.':'The city clock stays paused while the art loads.'}</p><div><button onClick={onDirectory}>Open address book →</button>{artState==='failed'&&<button onClick={()=>setAttempt(n=>n+1)}>Retry artwork</button>}</div></div>}<div className="street-inspect">{paintedBuildings.map(b=><button key={b.id} aria-pressed={selected===b.id} onClick={()=>onSelect(b.id)}>{b.name}</button>)}<button aria-pressed={motion} onClick={()=>{localStorage.setItem('black-ledger-motion',motion?'off':'on');setMotion(!motion)}}>{motion?'Pause ambience':'Resume ambience'}</button></div></div>
}
